"""
Application constants.
"""
from app.constants.notification_types import (
    ORDER_CREATED,
    ORDER_COMPLETED,
    TASK_OPENED,
    TASK_ASSIGNED,
    TASK_CLAIMED,
    TASK_COMPLETED,
    TASK_AUTO_CLOSED,
    TASK_OVERDUE,
    INVENTORY_LOW,
    INVENTORY_RESTOCKED,
    SALE_RECORDED,
    SYSTEM_ALERT,
    TOAST_NOTIFICATION_TYPES,
    SILENT_NOTIFICATION_TYPES,
)
from app.constants.order_roles import ORDER_TYPE_ROLES

__all__ = [
    "ORDER_CREATED",
    "ORDER_COMPLETED",
    "TASK_OPENED",
    "TASK_ASSIGNED",
    "TASK_CLAIMED",
    "TASK_COMPLETED",
    "TASK_AUTO_CLOSED",
    "TASK_OVERDUE",
    "INVENTORY_LOW",
    "INVENTORY_RESTOCKED",
    "SALE_RECORDED",
    "SYSTEM_ALERT",
    "TOAST_NOTIFICATION_TYPES",
    "SILENT_NOTIFICATION_TYPES",
    "ORDER_TYPE_ROLES",
]
